### ISSUE TITLE
one-to-one (belongs-to) relations

### ISSUE THREAD

**Issue by jmayaalv** [exoscale/seql#13]
Hi, what's the recommended way to represent one-to-one relations? I couldn't find a way on the doc nor the code. 

Thanks

**Comment by pyr** [comment]
Hi @jmayaalv ,

There is no support for one-to-one relations at the moment. 
If you want to give a shot at implementing them, you would have to extend the multi-method here:

https://github.com/exoscale/seql/blob/master/src/seql/core.clj#L55-L67

**Comment by jmayaalv** [comment]
Thanks for confirming. I will work on it in the next few days. 

Regards
