### ISSUE TITLE
Would next.jdbc make this easier?

### ISSUE THREAD

**Issue by seancorfield** [exoscale/seql#3]
One of the big differences between `clojure.java.jdbc` and `next.jdbc` is that the latter, by default, returns namespace-qualified keys in hash maps from all operations. In general, that's the table name as the qualifier and the column name as the keyword. Example:
```clojure
  (require '[honeysql.helpers :as h] '[honeysql.core :as hc])
  (jdbc/execute! datasource
                 (-> (h/select :user.id :user.username :status.name)
                     (h/from :user)
                     (h/join :status [:= :user.statusid :status.id])
                     (h/where [:in :user.id [9 10]])
                     (hc/format))))
;=>
[{:user/id 9, :user/username "derekpope", :status/name "approved"}
 {:user/id 10, :user/username "hardingvang", :status/name "approved"}]
```
This would (should?) allow you to avoid encoding entity names into aliases since they'd already come back that way in the queries.

Note that `next.jdbc` would require a (slightly) different format of the `:jdbc` value in the `env` -- I'd recommend assuming a `javax.sql.DataSource` (or a pooled data source object) directly there.

I'd be happy to work with you on converting `seql` over to `next.jdbc` -- as well as considering any changes you might want to be made to HoneySQL and/or `next.jdbc`, since I maintain both of those now. I suspect a change to HoneySQL that would help, would be to accept `:user/id` etc directly and treat them as `:user.id` etc?

**Comment by seancorfield** [comment]
For that last point, see https://github.com/jkk/honeysql/issues/249

**Comment by seancorfield** [comment]
With that change in HoneySQL, we get:
```clojure
  (jdbc/execute! datasource
                 (-> (h/select :user/id :user/username :status/name)
                     (h/from :user)
                     (h/join :status [:= :user/statusid :status/id])
                     (h/where [:in :user/id [9 10]])
                     (hc/format :namespace-as-table? true))))
```
(producing the same output as above)

**Comment by seancorfield** [comment]
`honeysql "0.9.8"` is on Clojars with this change if you want to try it out.

**Comment by pyr** [comment]
Hi @seancorfield,

Thanks for taking a look and suggesting `next.jdbc`, after a first look, a number of things would make things easier and faster were we to switch to `next.jdbc`. I will look into doing so.

`next.jdbc/plan` makes it look like it would improve the situation for `recompose-relations`. Specific `qualifier-fn` and `label-fn` for queries would help drastically too.

I'll work on an adaptation for a subsequent release.

**Comment by seancorfield** [comment]
Happy to help. Feel free to hit me up on Slack via DM if you have any questions.

**Comment by pyr** [comment]
seql `0.1.6` now runs on top of `next.jdbc` thanks for the nudge @seancorfield

**Comment by seancorfield** [comment]
Excellent! Thank you, @pyr ! Did anything come out of that work that would suggest enhancements to `next.jdbc` to make things easier for you?

**Comment by pyr** [comment]
@mpenet did the inital shot with the least possible amount of changes. Now we can look at gradually remove code and benefit from `next.jdbc` features
